<a href="https://colab.research.google.com/github/ramgeethatamatam-rgb/EDA_masai/blob/main/EDA_Workshop_Masai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests

url = "https://api.themoviedb.org/3/authentication"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNWRiZGZkZGM4MTQxMWFiZWQ3MjJmMWM0MjU5NmNiZCIsIm5iZiI6MTc3Mzc1MDMxOC43MDgsInN1YiI6IjY5Yjk0ODJlYTQ5NWIxYTgwNzliMmI2ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Bgct-PW1964ptAjwewxBMfJaHDf9N9kiyQNOy1KFhH8"
}

response = requests.get(url, headers=headers)

print(response.text)

{"success":true}

In [ ]:
import requests
from google.colab import userdata

# Get API key from Colab secrets
api_key = userdata.get('TMDB_API_KEY')

url = "https://api.themoviedb.org/3/authentication"

params = {
    "api_key": api_key
}

response = requests.get(url, params=params)

print(response.json())

{'success': True}

In [ ]:
import requests

url = "https://api.themoviedb.org/3/genre/movie/list"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNWRiZGZkZGM4MTQxMWFiZWQ3MjJmMWM0MjU5NmNiZCIsIm5iZiI6MTc3Mzc1MDMxOC43MDgsInN1YiI6IjY5Yjk0ODJlYTQ5NWIxYTgwNzliMmI2ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Bgct-PW1964ptAjwewxBMfJaHDf9N9kiyQNOy1KFhH8"
}

response = requests.get(url, headers=headers)

print(response.text)

{"genres":[{"id":28,"name":"Action"},{"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"},{"id":99,"name":"Documentary"},{"id":18,"name":"Drama"},{"id":10751,"name":"Family"},{"id":14,"name":"Fantasy"},{"id":36,"name":"History"},{"id":27,"name":"Horror"},{"id":10402,"name":"Music"},{"id":9648,"name":"Mystery"},{"id":10749,"name":"Romance"},{"id":878,"name":"Science Fiction"},{"id":10770,"name":"TV Movie"},{"id":53,"name":"Thriller"},{"id":10752,"name":"War"},{"id":37,"name":"Western"}]}

In [ ]:
import pandas as pd
data = response.json()
genres_df = pd.DataFrame(data['genres'])   # extract genres list
genres_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [ ]:
genres_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [ ]:
import requests

url = "https://api.themoviedb.org/3/discover/movie"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNWRiZGZkZGM4MTQxMWFiZWQ3MjJmMWM0MjU5NmNiZCIsIm5iZiI6MTc3Mzc1MDMxOC43MDgsInN1YiI6IjY5Yjk0ODJlYTQ5NWIxYTgwNzliMmI2ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Bgct-PW1964ptAjwewxBMfJaHDf9N9kiyQNOy1KFhH8"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/6yeVcxFR0j08vlv2OlL6zbewm4D.jpg","genre_ids":[28,878,53],"id":1265609,"original_language":"en","original_title":"War Machine","overview":"On one last grueling mission during Army Ranger training, a combat engineer must lead his unit in a fight against a giant otherworldly killing machine.","popularity":472.8603,"poster_path":"/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg","release_date":"2026-02-12","title":"War Machine","video":false,"vote_average":7.226,"vote_count":864},{"adult":false,"backdrop_path":"/u6YE4rlEWOiYoqhPJuNvt5GHxgu.jpg","genre_ids":[28,80,53],"id":1290821,"original_language":"en","original_title":"Shelter","overview":"A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.","popularity":298.5287,"poster_path":"/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg","release_date":"2026-01-28","title":"Shelter","video":false,"vote_average":6.596,"vote_count":307},{"adult":false,"backdrop_path":"/hYgUkH7TusddHRtelj53I6gFOWR.jpg","genre_ids":[28,53],"id":799882,"original_language":"en","original_title":"The Bluff","overview":"When her tranquil life on a remote island is shattered by the return of her vengeful former captain, a skilled ex-pirate must confront her bloody past and unleash her deadly talents to save her family from a ruthless siege.","popularity":193.2064,"poster_path":"/w0jwjFmRu2or7LQqh1tSMFjq0At.jpg","release_date":"2026-02-17","title":"The Bluff","video":false,"vote_average":6.338,"vote_count":272},{"adult":false,"backdrop_path":"/lgotja3xMoJZbynwHfcQcJAEMWH.jpg","genre_ids":[16,35,12,10751,9648],"id":1084242,"original_language":"en","original_title":"Zootopia 2","overview":"After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.","popularity":171.7147,"poster_path":"/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg","release_date":"2025-11-26","title":"Zootopia 2","video":false,"vote_average":7.606,"vote_count":2190},{"adult":false,"backdrop_path":null,"genre_ids":[10749,18],"id":1523145,"original_language":"ru","original_title":"Твое сердце будет разбито","overview":"High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.","popularity":180.9994,"poster_path":"/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg","release_date":"2026-03-26","title":"Your Heart Will Be Broken","video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/2RrLuIfIzGWWIH8IAEo6o0IYHmx.jpg","genre_ids":[16,10751,878,35],"id":1327819,"original_language":"en","original_title":"Hoppers","overview":"Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.","popularity":148.4862,"poster_path":"/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg","release_date":"2026-03-04","title":"Hoppers","video":false,"vote_average":7.718,"vote_count":195},{"adult":false,"backdrop_path":"/u9jE0R1nvkmdWu3bt7Op8joPywa.jpg","genre_ids":[12,53,878],"id":840464,"original_language":"en","original_title":"Greenland 2: Migration","overview":"Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.","popularity":138.5129,"poster_path":"/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg","release_date":"2026-01-07","title":"Greenland 2: Migration","video":false,"vote_average":6.437,"vote_count":608},{"adult":false,"backdrop_path":"/7HKpc11uQfxnw0Y8tRUYn1fsKqE.jpg","genre_ids":[878,28,53],"id":1236153,"original_language":"en","original_title":"Mercy","overview":"In the near future, a detective stands on trial accused of murdering his wife. He has ninety minutes to prove his innocence to the advanced AI Judge he once championed, before it determines his fate.","popularity":127.805,"poster_path":"/pyok1kZJCfyuFapYXzHcy7BLlQa.jpg","release_date":"2026-01-20","title":"Mercy","video":false,"vote_average":7.102,"vote_count":736},{"adult":false,"backdrop_path":"/1gLFGrxHqQebqLWpISmoFR6XWtJ.jpg","genre_ids":[28,53],"id":1088434,"original_language":"en","original_title":"Hellfire","overview":"A drifter with a mysterious past arrives in a small town and finds the residents in the grip of a ruthless crime boss and realizes he has to help them.","popularity":115.2882,"poster_path":"/tQti9QTf13MfzNpXguijgNh7ojE.jpg","release_date":"2026-02-05","title":"Hellfire","video":false,"vote_average":6.904,"vote_count":57},{"adult":false,"backdrop_path":"/cz4vLJrmaV1zJlRYbxqtvLzeLWB.jpg","genre_ids":[28,35,80,9648],"id":1168190,"original_language":"en","original_title":"The Wrecking Crew","overview":"Estranged half-brothers Jonny and James reunite after their father's mysterious death. As they search for the truth, buried secrets reveal a conspiracy threatening to tear their family apart.","popularity":113.1466,"poster_path":"/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg","release_date":"2026-01-28","title":"The Wrecking Crew","video":false,"vote_average":6.874,"vote_count":787},{"adult":false,"backdrop_path":"/drRxbu2OHG0DEENptZ8wI5f0uEU.jpg","genre_ids":[878,28,35],"id":1119449,"original_language":"en","original_title":"Good Luck, Have Fun, Don't Die","overview":"A 'Man from the Future' arrives at an LA diner where he must recruit the precise combination of disgruntled patrons to join him on a one-night quest to save the world from the terminal threat of a rogue artificial intelligence.","popularity":102.3336,"poster_path":"/rWcfOdY7TU6lTdazWj0ebDZnAfO.jpg","release_date":"2026-02-13","title":"Good Luck, Have Fun, Don't Die","video":false,"vote_average":6.991,"vote_count":161},{"adult":false,"backdrop_path":"/lmns2jlRmATs8OGWKcCkgrbHLM4.jpg","genre_ids":[28,18],"id":1634301,"original_language":"te","original_title":"Vanaveera","overview":"A descendant of the Vanara clan is pushed into conflict when a modern-day Ravana seizes his only bike for an election rally. What starts as a petty injustice soon erupts into a fierce fight for self-respect and dignity.","popularity":102.0585,"poster_path":"/oBYExKI8E3bTzQjPkofhpV2EJon.jpg","release_date":"2026-02-13","title":"Vanaveera","video":false,"vote_average":7.0,"vote_count":3},{"adult":false,"backdrop_path":"/yJi6g0CnsqANLNuVaRX28tZxeHX.jpg","genre_ids":[27,9648],"id":1193501,"original_language":"en","original_title":"Whistle","overview":"A misfit group of unwitting high school students stumble upon a cursed object, an ancient Aztec Death Whistle. They discover that blowing the whistle and the terrifying sound it emits will summon their future deaths to hunt them down.","popularity":108.8578,"poster_path":"/84vAcFwxoObBuMWANWQXCg0Umg8.jpg","release_date":"2026-01-20","title":"Whistle","video":false,"vote_average":6.106,"vote_count":151},{"adult":false,"backdrop_path":"/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg","genre_ids":[878,53],"id":755898,"original_language":"en","original_title":"War of the Worlds","overview":"Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.","popularity":100.0098,"poster_path":"/yvirUYrva23IudARHn3mMGVxWqM.jpg","release_date":"2025-07-29","title":"War of the Worlds","video":false,"vote_average":4.164,"vote_count":922},{"adult":false,"backdrop_path":"/sdZSjtGUTSN8B3al5o0f2WoQfQQ.jpg","genre_ids":[878,12,14],"id":83533,"original_language":"en","original_title":"Avatar: Fire and Ash","overview":"In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.","popularity":107.3607,"poster_path":"/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg","release_date":"2025-12-17","title":"Avatar: Fire and Ash","video":false,"vote_average":7.3,"vote_count":1893},{"adult":false,"backdrop_path":"/vSQSYd2zZTqc0zmHImwWEGGluMI.jpg","genre_ids":[10749,18],"id":1316092,"original_language":"en","original_title":"\"Wuthering Heights\"","overview":"Tragedy strikes when Heathcliff falls in love with Catherine Earnshaw, a woman from a wealthy family in 18th-century England.","popularity":106.4394,"poster_path":"/3YBce6dTh1D5oCMITXk2S5QhPt.jpg","release_date":"2026-02-11","title":"\"Wuthering Heights\"","video":false,"vote_average":6.355,"vote_count":516},{"adult":false,"backdrop_path":"/ibK0sooxQwIeqS9tz4Tj0chyca9.jpg","genre_ids":[27,53],"id":1058710,"original_language":"en","original_title":"Bloodline Killer","overview":"Moira Cole endeavors to rebuild her shattered life after her family's murder at the hands of her deranged and obsessed cousin.","popularity":100.8622,"poster_path":"/wHmzCQwBzT6m8wtZdXHOIITn82B.jpg","release_date":"2024-04-26","title":"Bloodline Killer","video":false,"vote_average":5.6,"vote_count":40},{"adult":false,"backdrop_path":"/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg","genre_ids":[878,12,9648],"id":687163,"original_language":"en","original_title":"Project Hail Mary","overview":"Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.","popularity":100.5315,"poster_path":"/vOhW7Lbt4kZAqe0vJhVC4Ced9x2.jpg","release_date":"2026-03-19","title":"Project Hail Mary","video":false,"vote_average":8.7,"vote_count":43},{"adult":false,"backdrop_path":"/gmu4liRCTk5nKSiGL6XHFbsJvD8.jpg","genre_ids":[27],"id":1451398,"original_language":"ja","original_title":"カラダ探し THE LAST NIGHT","overview":"Three years after completing a deadly game, high schoolers trapped in a looping nightmare must survive brutal encounters and unravel a terrifying curse.","popularity":85.2386,"poster_path":"/5MEzNrfvfpSajhSRSA7Jtybu3Jr.jpg","release_date":"2025-09-05","title":"Re/Member: The Last Night","video":false,"vote_average":4.5,"vote_count":6},{"adult":false,"backdrop_path":"/lNYympQM5O6QSInusbyG9eJDIe4.jpg","genre_ids":[16,28,14],"id":1311031,"original_language":"ja","original_title":"劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来","overview":"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.","popularity":88.2849,"poster_path":"/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg","release_date":"2025-07-18","title":"Demon Slayer: Kimetsu no Yaiba Infinity Castle","video":false,"vote_average":7.7,"vote_count":762}],"total_pages":55707,"total_results":1114129}

In [ ]:
data = response.json()

movies_df = pd.DataFrame(data["results"])

movies_df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/6yeVcxFR0j08vlv2OlL6zbewm4D.jpg,"[28, 878, 53]",1265609,en,War Machine,On one last grueling mission during Army Range...,472.8603,/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg,2026-02-12,War Machine,False,7.226,864
1,False,/u6YE4rlEWOiYoqhPJuNvt5GHxgu.jpg,"[28, 80, 53]",1290821,en,Shelter,A man living in self-imposed exile on a remote...,298.5287,/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg,2026-01-28,Shelter,False,6.596,307
2,False,/hYgUkH7TusddHRtelj53I6gFOWR.jpg,"[28, 53]",799882,en,The Bluff,When her tranquil life on a remote island is s...,193.2064,/w0jwjFmRu2or7LQqh1tSMFjq0At.jpg,2026-02-17,The Bluff,False,6.338,272
3,False,/lgotja3xMoJZbynwHfcQcJAEMWH.jpg,"[16, 35, 12, 10751, 9648]",1084242,en,Zootopia 2,After cracking the biggest case in Zootopia's ...,171.7147,/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg,2025-11-26,Zootopia 2,False,7.606,2190
4,False,None,"[10749, 18]",1523145,ru,Твое сердце будет разбито,High school student Polina is saved from bully...,180.9994,/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg,2026-03-26,Your Heart Will Be Broken,False,0.000,0

In [ ]:
import requests

url = "https://api.themoviedb.org/3/discover/movie"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNWRiZGZkZGM4MTQxMWFiZWQ3MjJmMWM0MjU5NmNiZCIsIm5iZiI6MTc3Mzc1MDMxOC43MDgsInN1YiI6IjY5Yjk0ODJlYTQ5NWIxYTgwNzliMmI2ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Bgct-PW1964ptAjwewxBMfJaHDf9N9kiyQNOy1KFhH8"
}


data = response.json()

movies_df = pd.DataFrame(data["results"])

movies_df.head()

KeyError: 'results'

# Start of the code

In [ ]:
import os, json, time, sqlite3, requests
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

In [ ]:
import requests
from google.colab import userdata

# Get API key from Colab secrets
API_KEY = userdata.get('TMDB_API_KEY')
if not API_KEY:
    raise EnvironmentError("TMDB_API_KEY not found! Add it to your .env file.")

e5dbdfddc81411abed722f1c42596cbd

In [ ]:

BASE = "https://api.themoviedb.org/3"
DB   = "movies.db"

print(f"API key loaded ({len(API_KEY)} chars)")

# ── Folders ───────────────────────────────────────────────────────────
Path("data/raw").mkdir(parents=True, exist_ok=True)

# ── Database schema ───────────────────────────────────────────────────
conn   = sqlite3.connect(DB)
cursor = conn.cursor()

cursor.executescript("""
    PRAGMA journal_mode=WAL;

    CREATE TABLE IF NOT EXISTS movies (
        movie_id          INTEGER PRIMARY KEY,
        title             TEXT NOT NULL,
        original_title    TEXT,
        release_date      TEXT,
        release_year      INTEGER,
        release_month     INTEGER,
        runtime           INTEGER,
        budget            REAL,
        revenue           REAL,
        vote_average      REAL,
        vote_count        INTEGER,
        popularity        REAL,
        original_language TEXT,
        overview          TEXT,
        tagline           TEXT,
        is_franchise      INTEGER DEFAULT 0,
        collection_name   TEXT,
        fetched_at        TEXT
    );

    CREATE TABLE IF NOT EXISTS genres (
        genre_id   INTEGER PRIMARY KEY,
        genre_name TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS movie_genres (
        movie_id   INTEGER,
        genre_id   INTEGER,
        genre_name TEXT,
        PRIMARY KEY (movie_id, genre_id),
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
        FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
    );

    CREATE TABLE IF NOT EXISTS cast (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        movie_id      INTEGER,
        actor_name    TEXT,
        character     TEXT,
        billing_order INTEGER,
        person_id     INTEGER,
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
    );

    CREATE TABLE IF NOT EXISTS directors (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        movie_id      INTEGER UNIQUE,
        director_name TEXT,
        person_id     INTEGER,
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
    );
""")
conn.commit()
print("Database and tables ready.")

API key loaded (32 chars)
Database and tables ready.

In [ ]:
# ── Fetch genres ──────────────────────────────────────────────────────
r = requests.get(f"{BASE}/genre/movie/list", params={"api_key": API_KEY}, timeout=10)
r.raise_for_status()
genres_data = r.json()["genres"]

In [ ]:
cursor.executemany(
    "INSERT OR IGNORE INTO genres (genre_id, genre_name) VALUES (?, ?)",
    [(g["id"], g["name"]) for g in genres_data]
)
conn.commit()
print(f"Stored {len(genres_data)} genres.")

Stored 19 genres.

Discovering 'most voted' (50 pages)... total unique so far: 1000
Discovering 'highest revenue' (25 pages)... total unique so far: 1097
Discovering 'highest rated' (25 pages)... total unique so far: 1450
Discovering 'most popular recent' (20 pages)... total unique so far: 1602

Pass 1 done: 1602 unique movies discovered.

In [ ]:
# ── Helper functions ──────────────────────────────────────────────────
def extract_director(crew_list):
    for member in crew_list:
        if member.get("job") == "Director":
            return member.get("name"), member.get("id")
    return None, None


def parse_year_month(date_str):
    if not date_str:
        return None, None
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.year, dt.month
    except (ValueError, TypeError):
        return None, None


def already_fetched(conn, movie_id):
    return conn.execute("SELECT 1 FROM movies WHERE movie_id=?", (movie_id,)).fetchone() is not None


def insert_movie(conn, data, credits):
    cur = conn.cursor()
    mid = data["id"]
    year, month = parse_year_month(data.get("release_date"))
    collection = data.get("belongs_to_collection")
    is_franchise = 1 if collection else 0
    collection_name = collection["name"] if collection else None

    cur.execute("""
        INSERT OR REPLACE INTO movies (
            movie_id, title, original_title, release_date,
            release_year, release_month, runtime, budget, revenue,
            vote_average, vote_count, popularity, original_language,
            overview, tagline, is_franchise, collection_name, fetched_at
        ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        mid, data.get("title"), data.get("original_title"), data.get("release_date"),
        year, month, data.get("runtime"), data.get("budget"), data.get("revenue"),
        data.get("vote_average"), data.get("vote_count"), data.get("popularity"),
        data.get("original_language"), data.get("overview"), data.get("tagline"),
        is_franchise, collection_name, datetime.now().isoformat(),
    ))

    for genre in data.get("genres", []):
        cur.execute(
            "INSERT OR IGNORE INTO movie_genres (movie_id, genre_id, genre_name) VALUES (?,?,?)",
            (mid, genre["id"], genre["name"]),
        )

    for actor in credits.get("cast", [])[:5]:
        cur.execute(
            "INSERT OR IGNORE INTO cast (movie_id, actor_name, character, billing_order, person_id) VALUES (?,?,?,?,?)",
            (mid, actor.get("name"), actor.get("character"), actor.get("order"), actor.get("id")),
        )

    director_name, director_id = extract_director(credits.get("crew", []))
    if director_name:
        cur.execute(
            "INSERT OR REPLACE INTO directors (movie_id, director_name, person_id) VALUES (?,?,?)",
            (mid, director_name, director_id),
        )


# ── Pass 2: Fetch full details + credits ──────────────────────────────
movie_ids = list(all_discovered.keys())
total     = len(movie_ids)
success = skipped = errors = 0

print(f"\nPass 2: Fetching details for {total} movies (~{total * 0.125 / 60:.0f} min)...")

for i, movie_id in enumerate(movie_ids):
    if already_fetched(conn, movie_id):
        skipped += 1
        continue

    try:
        r = requests.get(
            f"{BASE}/movie/{movie_id}",
            params={"api_key": API_KEY, "append_to_response": "credits"},
            timeout=15,
        )
        if r.status_code == 404:
            errors += 1
            continue

        r.raise_for_status()
        data = r.json()
        credits = data.pop("credits", {"cast": [], "crew": []})

        insert_movie(conn, data, credits)
        conn.commit()
        success += 1

        if success % 100 == 0:
            pct = (i + 1) / total * 100
            print(f"  [{pct:>5.1f}%]  {success} fetched  {skipped} skipped  {errors} errors")

        time.sleep(0.125)

    except requests.exceptions.Timeout:
        print(f"  Timeout on {movie_id}")
        errors += 1
        time.sleep(1)
    except requests.exceptions.HTTPError as e:
        if "429" in str(e):
            print("  Rate limited — sleeping 10s")
            time.sleep(10)
        else:
            errors += 1
    except Exception:
        errors += 1
        time.sleep(0.5)

print(f"\nPass 2 done!  Fetched: {success:,}  Skipped: {skipped:,}  Errors: {errors:,}")

# ── Verify ────────────────────────────────────────────────────────────
print(f"\n{'Table':<15} {'Rows':>8}")
print("-" * 25)
for table in ["movies", "genres", "movie_genres", "cast", "directors"]:
    count = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(f"  {table:<15} {count:>7,}")

conn.close()
print(f"\nDone. Database saved at: {DB}")

Pass 2: Fetching details for 1602 movies (~3 min)...
  [  6.2%]  100 fetched  0 skipped  0 errors
  [ 12.5%]  200 fetched  0 skipped  0 errors
  [ 18.7%]  300 fetched  0 skipped  0 errors
  [ 25.0%]  400 fetched  0 skipped  0 errors
  [ 31.2%]  500 fetched  0 skipped  0 errors
  [ 37.5%]  600 fetched  0 skipped  0 errors
  [ 43.7%]  700 fetched  0 skipped  0 errors
  [ 49.9%]  800 fetched  0 skipped  0 errors
  [ 56.2%]  900 fetched  0 skipped  0 errors
  [ 62.4%]  1000 fetched  0 skipped  0 errors
  [ 68.7%]  1100 fetched  0 skipped  0 errors
  [ 74.9%]  1200 fetched  0 skipped  0 errors
  [ 81.1%]  1300 fetched  0 skipped  0 errors
  [ 87.4%]  1400 fetched  0 skipped  0 errors
  [ 93.6%]  1500 fetched  0 skipped  0 errors
  [ 99.9%]  1600 fetched  0 skipped  0 errors

Pass 2 done!  Fetched: 1,602  Skipped: 0  Errors: 0

Table               Rows
-------------------------
  movies            1,602
  genres               19
  movie_genres      4,454
  cast              7,928
  directors         1,600

Done. Database saved at: movies.db

In [ ]:
import sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

# Seaborn theme for all plots
sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)
%matplotlib inline

print("Libraries loaded.")

Libraries loaded.

In [ ]:
conn = sqlite3.connect("movies.db")

df_movies       = pd.read_sql("SELECT * FROM movies", conn)
df_genres       = pd.read_sql("SELECT * FROM genres", conn)
df_movie_genres = pd.read_sql("SELECT * FROM movie_genres", conn)
df_cast         = pd.read_sql("SELECT * FROM cast", conn)
df_directors    = pd.read_sql("SELECT * FROM directors", conn)

conn.close()

for name, d in [("movies", df_movies), ("genres", df_genres),
                ("movie_genres", df_movie_genres), ("cast", df_cast),
                ("directors", df_directors)]:
    print(f"  {name:<15} {d.shape}")

  movies          (1602, 18)
  genres          (19, 2)
  movie_genres    (4454, 3)
  cast            (7928, 6)
  directors       (1600, 4)

In [ ]:
df_directors

        id  movie_id      director_name  person_id
0        1    157336  Christopher Nolan        525
1        2     27205  Christopher Nolan        525
2        3     24428        Joss Whedon      12891
3        4       155  Christopher Nolan        525
4        5     19995      James Cameron       2710
...    ...       ...                ...        ...
1595  1596     13600          Gil Kenan      57193
1596  1597    929590       Alex Garland       2036
1597  1598      2288       Mike Nichols       5342
1598  1599      9779         Ken Kwapis      29009
1599  1600   1294203      Dani Girdwood    2442185

[1600 rows x 4 columns]

In [ ]:
df_cast

,id,movie_id,actor_name,character,billing_order,person_id
0,1,157336,Matthew McConaughey,Cooper,0,10297
1,2,157336,Anne Hathaway,Brand,1,1813
2,3,157336,Michael Caine,Professor Brand,2,3895
3,4,157336,Jessica Chastain,Murph,3,83002
4,5,157336,Casey Affleck,Tom,4,1893
...,...,...,...,...,...,...
7923,7924,1294203,Asha Banks,Noah,0,3499290
7924,7925,1294203,Matthew Broome,Nick,1,3912097
7925,7926,1294203,Eve Macklin,Ella,2,1092908
7926,7927,1294203,Ray Fearon,William,3,56650
7927,7928,1294203,Enva Lewis,Jenna,4,4356302

In [ ]:
df_movie_genres[df_movie_genres['movie_id'] == 11]

     movie_id  genre_id       genre_name
127        11        12        Adventure
128        11        28           Action
129        11       878  Science Fiction

In [ ]:
df_movie_genres

      movie_id  genre_id       genre_name
0       157336        12        Adventure
1       157336        18            Drama
2       157336       878  Science Fiction
3        27205        28           Action
4        27205       878  Science Fiction
...        ...       ...              ...
4449      9779        18            Drama
4450      9779        35           Comedy
4451      9779     10749          Romance
4452   1294203        18            Drama
4453   1294203     10749          Romance

[4454 rows x 3 columns]

In [ ]:
genres_agg = (
    df_movie_genres.groupby("movie_id")["genre_name"]
    .agg(lambda x: ", ".join(sorted(x)))
    .reset_index()
    .rename(columns={"genre_name": "genres"})
)
genres_agg

      movie_id                              genres
0           11  Action, Adventure, Science Fiction
1           12        Adventure, Animation, Family
2           13              Comedy, Drama, Romance
3           14                               Drama
4           15                      Drama, Mystery
...        ...                                 ...
1597   1408208                     Horror, Mystery
1598   1412113                         Documentary
1599   1419406      Action, Crime, Drama, Thriller
1600   1456349     Crime, Drama, Mystery, Thriller
1601   1480382                               Drama

[1602 rows x 2 columns]

In [ ]:
df_genres[df_genres['genre_id']== 11]

Empty DataFrame
Columns: [genre_id, genre_name]
Index: []

In [ ]:
df_movies

,movie_id,title,original_title,release_date,release_year,release_month,runtime,budget,revenue,vote_average,vote_count,popularity,original_language,overview,tagline,is_franchise,collection_name,fetched_at
0,11,Star Wars,Star Wars,1977-05-25,1977,5,121,11000000.0,775398007.0,8.201,22049,20.4698,en,Princess Leia is captured and held hostage by ...,"A long time ago in a galaxy far, far away...",1,Star Wars Collection,2026-03-17T15:47:20.541517
1,12,Finding Nemo,Finding Nemo,2003-05-30,2003,5,100,94000000.0,940335536.0,7.817,20355,15.6778,en,"Nemo, an adventurous young clownfish, is unexp...",There are 3.7 trillion fish in the ocean. They...,1,Finding Nemo Collection,2026-03-17T15:47:24.481428
2,13,Forrest Gump,Forrest Gump,1994-06-23,1994,6,142,55000000.0,677387716.0,8.463,29378,25.0402,en,A man with a low IQ has accomplished great thi...,The world will never be the same once you've s...,0,None,2026-03-17T15:47:13.598438
3,14,American Beauty,American Beauty,1999-09-15,1999,9,122,15000000.0,356296601.0,8.000,12873,10.4014,en,"Lester Burnham, a depressed suburban father in...",... look closer,0,None,2026-03-17T15:47:57.990402
4,15,Citizen Kane,Citizen Kane,1941-04-17,1941,4,119,839727.0,23218000.0,7.978,5966,4.7630,en,Newspaper magnate Charles Foster Kane is taken...,Some called him a hero...others called him a h...,0,None,2026-03-17T15:50:13.838163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597,1408208,Exit 8,８番出口,2025-08-28,2025,8,95,0.0,39142423.0,6.465,231,13.1064,ja,A man becomes increasingly desperate when he r...,Turn back.,0,None,2026-03-17T15:52:47.600353
1598,1412113,Squid Game: Making Season 2,오징어 게임: 시즌2 제작 이야기,2025-01-02,2025,1,28,0.0,0.0,8.402,442,5.7189,ko,"From set designs to character arcs, get exclus...",,0,None,2026-03-17T15:51:16.270381
1599,1419406,The Shadow's Edge,The Shadow's Edge,2025-08-16,2025,8,142,0.0,174400000.0,7.210,497,78.6013,zh,Macau Police brings the tracking expert police...,He's training a new generation of law enforcer...,0,None,2026-03-17T15:52:26.981048
1600,1456349,It Was Just an Accident,Un simple accident,2025-10-01,2025,10,103,6000000.0,9602793.0,7.186,451,15.1428,fr,An unassuming mechanic is reminded of his time...,,0,None,2026-03-17T15:52:44.279273
1601,1480382,The Voice of Hind Rajab,صوت هند رجب,2025-09-10,2025,9,89,0.0,5058441.0,8.100,225,14.6489,ar,"January 29, 2024. Red Crescent volunteers rece...",The voices on the phone are real.,0,None,2026-03-17T15:51:38.033414

In [ ]:
conn = sqlite3.connect("movies.db")

df_movies       = pd.read_sql("SELECT * FROM movies", conn)
df_genres       = pd.read_sql("SELECT * FROM genres", conn)
df_movie_genres = pd.read_sql("SELECT * FROM movie_genres", conn)
df_cast         = pd.read_sql("SELECT * FROM cast", conn)
df_directors    = pd.read_sql("SELECT * FROM directors", conn)

conn.close()

for name, d in [("movies", df_movies), ("genres", df_genres),
                ("movie_genres", df_movie_genres), ("cast", df_cast),
                ("directors", df_directors)]:
    print(f"  {name:<15} {d.shape}")


# Aggregate genres into comma-separated string per movie
genres_agg = (
    df_movie_genres.groupby("movie_id")["genre_name"]
    .agg(lambda x: ", ".join(sorted(x)))
    .reset_index()
    .rename(columns={"genre_name": "genres"})
)

# Aggregate top 5 cast into comma-separated string per movie
cast_agg = (
    df_cast.sort_values(["movie_id", "billing_order"])
    .groupby("movie_id")["actor_name"]
    .agg(lambda x: ", ".join(x))
    .reset_index()
    .rename(columns={"actor_name": "top_cast"})
)

directors_slim = df_directors[["movie_id", "director_name"]].copy()

# Merge everything
df = (
    df_movies
    .merge(genres_agg, on="movie_id", how="left")
    .merge(cast_agg, on="movie_id", how="left")
    .merge(directors_slim, on="movie_id", how="left")
)
df

  movies          (1602, 18)
  genres          (19, 2)
  movie_genres    (4454, 3)
  cast            (7928, 6)
  directors       (1600, 4)

,movie_id,title,original_title,release_date,release_year,release_month,runtime,budget,revenue,vote_average,...,popularity,original_language,overview,tagline,is_franchise,collection_name,fetched_at,genres,top_cast,director_name
0,11,Star Wars,Star Wars,1977-05-25,1977,5,121,11000000.0,775398007.0,8.201,...,20.4698,en,Princess Leia is captured and held hostage by ...,"A long time ago in a galaxy far, far away...",1,Star Wars Collection,2026-03-17T15:47:20.541517,"Action, Adventure, Science Fiction","Mark Hamill, Harrison Ford, Carrie Fisher, Pet...",George Lucas
1,12,Finding Nemo,Finding Nemo,2003-05-30,2003,5,100,94000000.0,940335536.0,7.817,...,15.6778,en,"Nemo, an adventurous young clownfish, is unexp...",There are 3.7 trillion fish in the ocean. They...,1,Finding Nemo Collection,2026-03-17T15:47:24.481428,"Adventure, Animation, Family","Albert Brooks, Ellen DeGeneres, Alexander Goul...",Andrew Stanton
2,13,Forrest Gump,Forrest Gump,1994-06-23,1994,6,142,55000000.0,677387716.0,8.463,...,25.0402,en,A man with a low IQ has accomplished great thi...,The world will never be the same once you've s...,0,None,2026-03-17T15:47:13.598438,"Comedy, Drama, Romance","Tom Hanks, Robin Wright, Gary Sinise, Sally Fi...",Robert Zemeckis
3,14,American Beauty,American Beauty,1999-09-15,1999,9,122,15000000.0,356296601.0,8.000,...,10.4014,en,"Lester Burnham, a depressed suburban father in...",... look closer,0,None,2026-03-17T15:47:57.990402,Drama,"Kevin Spacey, Annette Bening, Thora Birch, Wes...",Sam Mendes
4,15,Citizen Kane,Citizen Kane,1941-04-17,1941,4,119,839727.0,23218000.0,7.978,...,4.7630,en,Newspaper magnate Charles Foster Kane is taken...,Some called him a hero...others called him a h...,0,None,2026-03-17T15:50:13.838163,"Drama, Mystery","Orson Welles, Joseph Cotten, Dorothy Comingore...",Orson Welles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597,1408208,Exit 8,８番出口,2025-08-28,2025,8,95,0.0,39142423.0,6.465,...,13.1064,ja,A man becomes increasingly desperate when he r...,Turn back.,0,None,2026-03-17T15:52:47.600353,"Horror, Mystery","Kazunari Ninomiya, Yamato Kochi, Naru Asanuma,...",Genki Kawamura
1598,1412113,Squid Game: Making Season 2,오징어 게임: 시즌2 제작 이야기,2025-01-02,2025,1,28,0.0,0.0,8.402,...,5.7189,ko,"From set designs to character arcs, get exclus...",,0,None,2026-03-17T15:51:16.270381,Documentary,"Hwang Dong-hyuk, Lee Jung-jae, Lee Byung-hun, ...",NaN
1599,1419406,The Shadow's Edge,The Shadow's Edge,2025-08-16,2025,8,142,0.0,174400000.0,7.210,...,78.6013,zh,Macau Police brings the tracking expert police...,He's training a new generation of law enforcer...,0,None,2026-03-17T15:52:26.981048,"Action, Crime, Drama, Thriller","Jackie Chan, Zhang Zifeng, Tony Leung Ka-fai, ...",Larry Yang
1600,1456349,It Was Just an Accident,Un simple accident,2025-10-01,2025,10,103,6000000.0,9602793.0,7.186,...,15.1428,fr,An unassuming mechanic is reminded of his time...,,0,None,2026-03-17T15:52:44.279273,"Crime, Drama, Mystery, Thriller","Vahid Mobasseri, Mariam Afshari, Ebrahim Azizi...",Jafar Panahi
1601,1480382,The Voice of Hind Rajab,صوت هند رجب,2025-09-10,2025,9,89,0.0,5058441.0,8.100,...,14.6489,ar,"January 29, 2024. Red Crescent volunteers rece...",The voices on the phone are real.,0,None,2026-03-17T15:51:38.033414,Drama,"Hind Rajab, Motaz Malhees, Saja Kilani, Amer H...",Kaouther Ben Hania

# Final Code you can try

In [ ]:
"""
TMDB Data Pipeline — Pull → Clean → Store in SQLite
Fetches ~2,000 movies from TMDB and stores them in movies.db with 5 tables.
"""

import os, json, time, sqlite3, requests
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# ── Config ────────────────────────────────────────────────────────────
load_dotenv()
API_KEY = os.environ.get("TMDB_API_KEY")
if not API_KEY:
    raise EnvironmentError("TMDB_API_KEY not found! Add it to your .env file.")

BASE = "https://api.themoviedb.org/3"
DB   = "movies.db"

print(f"API key loaded ({len(API_KEY)} chars)")

# ── Folders ───────────────────────────────────────────────────────────
Path("data/raw").mkdir(parents=True, exist_ok=True)

# ── Database schema ───────────────────────────────────────────────────
conn   = sqlite3.connect(DB)
cursor = conn.cursor()

cursor.executescript("""
    PRAGMA journal_mode=WAL;

    CREATE TABLE IF NOT EXISTS movies (
        movie_id          INTEGER PRIMARY KEY,
        title             TEXT NOT NULL,
        original_title    TEXT,
        release_date      TEXT,
        release_year      INTEGER,
        release_month     INTEGER,
        runtime           INTEGER,
        budget            REAL,
        revenue           REAL,
        vote_average      REAL,
        vote_count        INTEGER,
        popularity        REAL,
        original_language TEXT,
        overview          TEXT,
        tagline           TEXT,
        is_franchise      INTEGER DEFAULT 0,
        collection_name   TEXT,
        fetched_at        TEXT
    );

    CREATE TABLE IF NOT EXISTS genres (
        genre_id   INTEGER PRIMARY KEY,
        genre_name TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS movie_genres (
        movie_id   INTEGER,
        genre_id   INTEGER,
        genre_name TEXT,
        PRIMARY KEY (movie_id, genre_id),
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
        FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
    );

    CREATE TABLE IF NOT EXISTS cast (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        movie_id      INTEGER,
        actor_name    TEXT,
        character     TEXT,
        billing_order INTEGER,
        person_id     INTEGER,
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
    );

    CREATE TABLE IF NOT EXISTS directors (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        movie_id      INTEGER UNIQUE,
        director_name TEXT,
        person_id     INTEGER,
        FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
    );
""")
conn.commit()
print("Database and tables ready.")

# ── Fetch genres ──────────────────────────────────────────────────────
r = requests.get(f"{BASE}/genre/movie/list", params={"api_key": API_KEY}, timeout=10)
r.raise_for_status()
genres_data = r.json()["genres"]

cursor.executemany(
    "INSERT OR IGNORE INTO genres (genre_id, genre_name) VALUES (?, ?)",
    [(g["id"], g["name"]) for g in genres_data]
)
conn.commit()
print(f"Stored {len(genres_data)} genres.")

# ── Pass 1: Discover movie IDs ───────────────────────────────────────
DISCOVER_CONFIGS = [
    ("vote_count.desc",   50, "most voted"),
    ("revenue.desc",      25, "highest revenue"),
    ("vote_average.desc", 25, "highest rated"),
    ("popularity.desc",   20, "most popular recent"),
]

all_discovered = {}

for sort_by, pages, label in DISCOVER_CONFIGS:
    print(f"Discovering '{label}' ({pages} pages)...", end=" ", flush=True)
    for page in range(1, pages + 1):
        try:
            r = requests.get(
                f"{BASE}/discover/movie",
                params={"api_key": API_KEY, "sort_by": sort_by, "vote_count.gte": 200, "page": page},
                timeout=15,
            )
            r.raise_for_status()
            for movie in r.json().get("results", []):
                all_discovered[movie["id"]] = movie
            time.sleep(0.125)
        except Exception as e:
            print(f"\n  Error page {page}: {e}")
            time.sleep(1)
    print(f"total unique so far: {len(all_discovered)}")

with open("data/raw/discovered_ids.json", "w") as f:
    json.dump(list(all_discovered.keys()), f)
print(f"\nPass 1 done: {len(all_discovered)} unique movies discovered.")


# ── Helper functions ──────────────────────────────────────────────────
def extract_director(crew_list):
    for member in crew_list:
        if member.get("job") == "Director":
            return member.get("name"), member.get("id")
    return None, None


def parse_year_month(date_str):
    if not date_str:
        return None, None
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.year, dt.month
    except (ValueError, TypeError):
        return None, None


def already_fetched(conn, movie_id):
    return conn.execute("SELECT 1 FROM movies WHERE movie_id=?", (movie_id,)).fetchone() is not None


def insert_movie(conn, data, credits):
    cur = conn.cursor()
    mid = data["id"]
    year, month = parse_year_month(data.get("release_date"))
    collection = data.get("belongs_to_collection")
    is_franchise = 1 if collection else 0
    collection_name = collection["name"] if collection else None

    cur.execute("""
        INSERT OR REPLACE INTO movies (
            movie_id, title, original_title, release_date,
            release_year, release_month, runtime, budget, revenue,
            vote_average, vote_count, popularity, original_language,
            overview, tagline, is_franchise, collection_name, fetched_at
        ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        mid, data.get("title"), data.get("original_title"), data.get("release_date"),
        year, month, data.get("runtime"), data.get("budget"), data.get("revenue"),
        data.get("vote_average"), data.get("vote_count"), data.get("popularity"),
        data.get("original_language"), data.get("overview"), data.get("tagline"),
        is_franchise, collection_name, datetime.now().isoformat(),
    ))

    for genre in data.get("genres", []):
        cur.execute(
            "INSERT OR IGNORE INTO movie_genres (movie_id, genre_id, genre_name) VALUES (?,?,?)",
            (mid, genre["id"], genre["name"]),
        )

    for actor in credits.get("cast", [])[:5]:
        cur.execute(
            "INSERT OR IGNORE INTO cast (movie_id, actor_name, character, billing_order, person_id) VALUES (?,?,?,?,?)",
            (mid, actor.get("name"), actor.get("character"), actor.get("order"), actor.get("id")),
        )

    director_name, director_id = extract_director(credits.get("crew", []))
    if director_name:
        cur.execute(
            "INSERT OR REPLACE INTO directors (movie_id, director_name, person_id) VALUES (?,?,?)",
            (mid, director_name, director_id),
        )


# ── Pass 2: Fetch full details + credits ──────────────────────────────
movie_ids = list(all_discovered.keys())
total     = len(movie_ids)
success = skipped = errors = 0

print(f"\nPass 2: Fetching details for {total} movies (~{total * 0.125 / 60:.0f} min)...")

for i, movie_id in enumerate(movie_ids):
    if already_fetched(conn, movie_id):
        skipped += 1
        continue

    try:
        r = requests.get(
            f"{BASE}/movie/{movie_id}",
            params={"api_key": API_KEY, "append_to_response": "credits"},
            timeout=15,
        )
        if r.status_code == 404:
            errors += 1
            continue

        r.raise_for_status()
        data = r.json()
        credits = data.pop("credits", {"cast": [], "crew": []})

        insert_movie(conn, data, credits)
        conn.commit()
        success += 1

        if success % 100 == 0:
            pct = (i + 1) / total * 100
            print(f"  [{pct:>5.1f}%]  {success} fetched  {skipped} skipped  {errors} errors")

        time.sleep(0.125)

    except requests.exceptions.Timeout:
        print(f"  Timeout on {movie_id}")
        errors += 1
        time.sleep(1)
    except requests.exceptions.HTTPError as e:
        if "429" in str(e):
            print("  Rate limited — sleeping 10s")
            time.sleep(10)
        else:
            errors += 1
    except Exception:
        errors += 1
        time.sleep(0.5)

print(f"\nPass 2 done!  Fetched: {success:,}  Skipped: {skipped:,}  Errors: {errors:,}")

# ── Verify ────────────────────────────────────────────────────────────
print(f"\n{'Table':<15} {'Rows':>8}")
print("-" * 25)
for table in ["movies", "genres", "movie_genres", "cast", "directors"]:
    count = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(f"  {table:<15} {count:>7,}")

conn.close()
print(f"\nDone. Database saved at: {DB}")

# EDA Part

In [ ]:
"""
TMDB EDA — Load, Merge, Clean, Explore & Plot
Loads all 5 tables from movies.db, merges into one DataFrame, then runs
exploratory analysis with visualisations for the workshop.
"""

import sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from pathlib import Path

sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)
Path("plots").mkdir(exist_ok=True)

DB = "movies.db"

# ── 1. Load all tables ───────────────────────────────────────────────
conn = sqlite3.connect(DB)

df_movies       = pd.read_sql("SELECT * FROM movies", conn)
df_genres       = pd.read_sql("SELECT * FROM genres", conn)
df_movie_genres = pd.read_sql("SELECT * FROM movie_genres", conn)
df_cast         = pd.read_sql("SELECT * FROM cast", conn)
df_directors    = pd.read_sql("SELECT * FROM directors", conn)

conn.close()

print("Tables loaded:")
for name, d in [("movies", df_movies), ("genres", df_genres),
                ("movie_genres", df_movie_genres), ("cast", df_cast),
                ("directors", df_directors)]:
    print(f"  {name:<15} {d.shape}")

# ── 2. Aggregate genres & cast per movie ─────────────────────────────
genres_agg = (
    df_movie_genres.groupby("movie_id")["genre_name"]
    .agg(lambda x: ", ".join(sorted(x)))
    .reset_index()
    .rename(columns={"genre_name": "genres"})
)

cast_agg = (
    df_cast.sort_values(["movie_id", "billing_order"])
    .groupby("movie_id")["actor_name"]
    .agg(lambda x: ", ".join(x))
    .reset_index()
    .rename(columns={"actor_name": "top_cast"})
)

directors_slim = df_directors[["movie_id", "director_name"]].copy()

# ── 3. Merge into one big DataFrame ──────────────────────────────────
df = (
    df_movies
    .merge(genres_agg, on="movie_id", how="left")
    .merge(cast_agg, on="movie_id", how="left")
    .merge(directors_slim, on="movie_id", how="left")
)

# ── 4. Clean: replace 0 with NaN for budget/revenue ─────────────────
df["budget"]  = df["budget"].replace(0, np.nan)
df["revenue"] = df["revenue"].replace(0, np.nan)

# Derived columns
df["profit"]     = df["revenue"] - df["budget"]
df["roi"]        = (df["profit"] / df["budget"]) * 100  # ROI as percentage
df["decade"]     = (df["release_year"] // 10 * 10).astype("Int64")

print(f"\nMerged DataFrame: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print(f"\nNull counts in key columns:")
for col in ["budget", "revenue", "runtime", "director_name", "genres", "top_cast"]:
    print(f"  {col:<20} {df[col].isna().sum()}")

# ── Helper to save plots ─────────────────────────────────────────────
def savefig(name):
    plt.tight_layout()
    plt.savefig(f"plots/{name}.png", dpi=150, bbox_inches="tight")
    print(f"  Saved plots/{name}.png")
    plt.close()

# ══════════════════════════════════════════════════════════════════════
# EDA PLOTS
# ══════════════════════════════════════════════════════════════════════

# ── Q1: Which genres have the most movies? ───────────────────────────
print("\nQ1: Genre distribution")
genre_counts = df_movie_genres["genre_name"].value_counts()

fig, ax = plt.subplots(figsize=(10, 6))
genre_counts.plot.barh(ax=ax, color=sns.color_palette("viridis", len(genre_counts)))
ax.set_xlabel("Number of Movies")
ax.set_title("Movies per Genre")
ax.invert_yaxis()
savefig("01_genre_distribution")

# ── Q2: Budget vs Revenue — does spending more earn more? ────────────
print("Q2: Budget vs Revenue scatter")
fin = df.dropna(subset=["budget", "revenue"])

fig, ax = plt.subplots(figsize=(10, 7))
scatter = ax.scatter(fin["budget"] / 1e6, fin["revenue"] / 1e6,
                     alpha=0.4, c=fin["vote_average"], cmap="RdYlGn", s=20)
ax.plot([0, fin["budget"].max() / 1e6], [0, fin["budget"].max() / 1e6],
        "r--", alpha=0.5, label="Break-even line")
ax.set_xlabel("Budget ($M)")
ax.set_ylabel("Revenue ($M)")
ax.set_title("Budget vs Revenue (color = rating)")
plt.colorbar(scatter, label="Vote Average")
ax.legend()
savefig("02_budget_vs_revenue")

# ── Q3: Rating distribution ──────────────────────────────────────────
print("Q3: Rating distribution")
fig, ax = plt.subplots(figsize=(10, 5))
ax.hist(df["vote_average"].dropna(), bins=40, edgecolor="white", color="#4C72B0")
ax.axvline(df["vote_average"].mean(), color="red", linestyle="--", label=f"Mean: {df['vote_average'].mean():.1f}")
ax.set_xlabel("Vote Average")
ax.set_ylabel("Count")
ax.set_title("Distribution of Movie Ratings")
ax.legend()
savefig("03_rating_distribution")

# ── Q4: Revenue by genre (box plot) ──────────────────────────────────
print("Q4: Revenue by genre")
genre_rev = df_movie_genres.merge(df[["movie_id", "revenue"]], on="movie_id")
genre_rev = genre_rev.dropna(subset=["revenue"])

top_genres = genre_rev["genre_name"].value_counts().head(10).index
genre_rev_top = genre_rev[genre_rev["genre_name"].isin(top_genres)]

fig, ax = plt.subplots(figsize=(12, 6))
order = genre_rev_top.groupby("genre_name")["revenue"].median().sort_values(ascending=False).index
sns.boxplot(data=genre_rev_top, x="genre_name", y="revenue", order=order, ax=ax, showfliers=False)
ax.set_ylabel("Revenue ($)")
ax.set_xlabel("")
ax.set_title("Revenue Distribution by Genre (top 10, outliers hidden)")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e6:.0f}M"))
plt.xticks(rotation=45, ha="right")
savefig("04_revenue_by_genre")

# ── Q5: How has average runtime changed over decades? ────────────────
print("Q5: Runtime over decades")
decade_runtime = df.dropna(subset=["decade", "runtime"]).groupby("decade")["runtime"].mean()

fig, ax = plt.subplots(figsize=(10, 5))
decade_runtime.plot(kind="bar", ax=ax, color="#55A868", edgecolor="white")
ax.set_ylabel("Average Runtime (min)")
ax.set_xlabel("Decade")
ax.set_title("Average Movie Runtime by Decade")
ax.set_xticklabels([str(int(x)) for x in decade_runtime.index], rotation=0)
savefig("05_runtime_by_decade")

# ── Q6: Franchise vs Standalone ──────────────────────────────────────
print("Q6: Franchise vs Standalone")
fran = df.dropna(subset=["revenue"])
fran["type"] = fran["is_franchise"].map({1: "Franchise", 0: "Standalone"})

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=fran, x="type", y="revenue", ax=axes[0], showfliers=False)
axes[0].set_title("Revenue: Franchise vs Standalone")
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e6:.0f}M"))
axes[0].set_xlabel("")

sns.boxplot(data=fran, x="type", y="vote_average", ax=axes[1], showfliers=False)
axes[1].set_title("Rating: Franchise vs Standalone")
axes[1].set_xlabel("")
savefig("06_franchise_vs_standalone")

# ── Q7: Best month to release a movie? ───────────────────────────────
print("Q7: Best release month")
monthly = df.dropna(subset=["release_month", "revenue"]).groupby("release_month").agg(
    avg_revenue=("revenue", "mean"),
    movie_count=("movie_id", "count"),
).reset_index()
month_names = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

fig, ax1 = plt.subplots(figsize=(10, 5))
ax1.bar(monthly["release_month"], monthly["avg_revenue"] / 1e6, color="#4C72B0", alpha=0.7, label="Avg Revenue")
ax1.set_ylabel("Avg Revenue ($M)")
ax1.set_xlabel("Release Month")
ax1.set_xticks(range(1, 13))
ax1.set_xticklabels(month_names)
ax1.set_title("Average Revenue & Movie Count by Release Month")

ax2 = ax1.twinx()
ax2.plot(monthly["release_month"], monthly["movie_count"], "o-", color="#C44E52", label="Movie Count")
ax2.set_ylabel("Number of Movies")

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper left")
savefig("07_best_release_month")

# ── Q8: Top 15 directors by avg rating (min 3 films) ────────────────
print("Q8: Top directors by rating")
dir_stats = (
    df.dropna(subset=["director_name"])
    .groupby("director_name")
    .agg(films=("movie_id", "count"), avg_rating=("vote_average", "mean"))
    .query("films >= 3")
    .sort_values("avg_rating", ascending=False)
    .head(15)
)

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(dir_stats.index, dir_stats["avg_rating"], color=sns.color_palette("coolwarm", len(dir_stats)))
ax.set_xlabel("Average Rating")
ax.set_title("Top 15 Directors by Avg Rating (min 3 films)")
ax.invert_yaxis()
for i, (val, films) in enumerate(zip(dir_stats["avg_rating"], dir_stats["films"])):
    ax.text(val + 0.05, i, f"{val:.1f} ({films} films)", va="center", fontsize=9)
savefig("08_top_directors_rating")

# ── Q9: Most appearing actors ────────────────────────────────────────
print("Q9: Most appearing actors")
actor_counts = df_cast["actor_name"].value_counts().head(20)

fig, ax = plt.subplots(figsize=(10, 6))
actor_counts.plot.barh(ax=ax, color=sns.color_palette("magma", len(actor_counts)))
ax.set_xlabel("Number of Movies (in top-5 billing)")
ax.set_title("Top 20 Most Appearing Actors")
ax.invert_yaxis()
savefig("09_top_actors")

# ── Q10: Correlation heatmap of numeric columns ─────────────────────
print("Q10: Correlation heatmap")
numeric_cols = ["budget", "revenue", "runtime", "vote_average", "vote_count", "popularity", "profit", "roi"]
corr = df[numeric_cols].corr()

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="RdBu_r", center=0, ax=ax, square=True)
ax.set_title("Correlation Heatmap of Numeric Features")
savefig("10_correlation_heatmap")

# ── Q11: Movies per year trend ───────────────────────────────────────
print("Q11: Movies per year")
yearly = df.dropna(subset=["release_year"])
yearly = yearly[yearly["release_year"].between(1970, 2025)]
year_counts = yearly.groupby("release_year").size()

fig, ax = plt.subplots(figsize=(12, 5))
ax.fill_between(year_counts.index, year_counts.values, alpha=0.3, color="#4C72B0")
ax.plot(year_counts.index, year_counts.values, color="#4C72B0", linewidth=2)
ax.set_xlabel("Year")
ax.set_ylabel("Number of Movies")
ax.set_title("Movies in Dataset per Year (1970–2025)")
savefig("11_movies_per_year")

# ── Q12: ROI — which low-budget films earned the most? ───────────────
print("Q12: Top ROI movies")
roi_df = df.dropna(subset=["roi", "budget"]).query("budget > 1e6").nlargest(15, "roi")

fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.barh(roi_df["title"], roi_df["roi"], color=sns.color_palette("YlOrRd_r", len(roi_df)))
ax.set_xlabel("ROI (%)")
ax.set_title("Top 15 Movies by ROI (budget > $1M)")
ax.invert_yaxis()
for i, (val, bud) in enumerate(zip(roi_df["roi"], roi_df["budget"])):
    ax.text(val + 50, i, f"{val:,.0f}% (${bud/1e6:.0f}M budget)", va="center", fontsize=8)
savefig("12_top_roi_movies")

# ── Summary stats ────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("SUMMARY STATISTICS")
print("=" * 60)
print(f"Total movies:          {len(df):,}")
print(f"With budget data:      {df['budget'].notna().sum():,}")
print(f"With revenue data:     {df['revenue'].notna().sum():,}")
print(f"Year range:            {df['release_year'].min():.0f} – {df['release_year'].max():.0f}")
print(f"Avg rating:            {df['vote_average'].mean():.2f}")
print(f"Avg runtime:           {df['runtime'].mean():.0f} min")
print(f"Franchise movies:      {df['is_franchise'].sum():,} ({df['is_franchise'].mean()*100:.1f}%)")
print(f"Unique directors:      {df['director_name'].nunique():,}")
print(f"Unique actors:         {df_cast['actor_name'].nunique():,}")
print(f"\nAll 12 plots saved to plots/ folder.")
print("Done!")